### ISSUE TITLE
Créer Fragment "Liste des concerts"

### ISSUE THREAD

**Issue by Diogo-Ferreira** [Diogo-Ferreira/Every_Shows#1]
Créer un fragment contenant une recyclerview représentant chaque concerts disponible.

Créer une classe modèle pour un concerts.

La liste des concerts peut être générer aléatoirement pour commencer.

**Comment by LumenH** [comment]
The commits below refer to this issue : 
d10578321fdb1dfe831345dfae97ce68e168cf7
1cb9724a6f5aefb273c44ca6c13d62d6706ee19c

**Comment by LumenH** [comment]
- [x] modifier le constructeur de la classe Show pour prendre en compte la date

**Comment by LumenH** [comment]
TODO : 
- [x] La taille des images des artistes doit être la même que celle des salles de concert
