### ISSUE TITLE
Base de données

### ISSUE THREAD

**Issue by Diogo-Ferreira** [Diogo-Ferreira/Every_Shows#2]
Créer une classe pour persister les artistes :
- Créer une classe modèle de base gérant la BDD
- Créer un modèle artiste, ou on peut sauver un artiste et le charger depuis la BDD.

Le moteur sera SQLite.

**Comment by Diogo-Ferreira** [comment]
Regarder[ le media store](https://developer.android.com/reference/android/provider/MediaStore.Audio.Artists.html) pour remplir cette base de données, même si android fait déjà tout le travail il reste quand même à filtrer les artistes (Ex. eminen, eminem feat xyz etc...).

De plus l'idéal serait de faire un service pour que l'application soit notifié lorsque de nouveaux artistes sont ajoutés.

**Comment by LumenH** [comment]
Finalement, la base de données ne sera utile que pour les notifications de nouveaux concertes. Car nous avons besoin de savoir quels concerts n'ont pas encore été présentés à l'utilisateur.
